name: concordia
channels:
- conda-forge
dependencies:
- typing-extensions
- attrs
- cattrs
- pandas >=1.1
- pandas-indexing
- openscm-units
- pyyaml
- xlrd >=2.0
- openpyxl
- matplotlib
- seaborn
- plotly
- pyomo
- pytest
- filelock
- deprecated
- pycountry
- dominate
- python-slugify
- seaborn
- tqdm
- jupytext
- colorlog
- ipykernel

# ptolemy dependencies
- netcdf4
- h5netcdf
- dask
- xarray
- pooch
- zarr
- flox
- pyogrio
- geopandas
- bottleneck
- cf_xarray

# raster generation
- rasterio
- rioxarray
- geoutils >=0.1.2 # Added that version lower-bound since they introduced a python 3.11 upper bound then, limiting our environment to python 3.11 effectively
- cartopy
- geopandas
- pyreadr

- pip
- pip:
  # Need to integrate new indexraster changes into ptolemy
  - git+https://github.com/gidden/ptolemy.git#egg=ptolemy-iamc
  - git+https://github.com/iiasa/aneris.git@workflow#egg=aneris-iamc
  - -e .[rescue]
